name: CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
        
    - name: install related packages
      run: |
	sudo apt install libboost-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=debug ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest

